### ISSUE TITLE
pcbdraw: no such option: --shrink

### ISSUE THREAD

**Issue by keshav-raj-trekker** [yaqwsx/Pinion#31]
Getting an error when attempting to generate. I am running it on Ubuntu 20.04 Kicad 6.0.5.
The following is the command I ran, and the output.

```
pinion generate --style rendered -b grover_system_ctlr_hw/grover_system_ctlr_hw.kicad_pcb -s pinion_template.yaml pinion_diagram.html
Usage: pcbdraw [OPTIONS] COMMAND [ARGS]...
Try 'pcbdraw --help' for help.

Error: No such option: --shrink
Traceback (most recent call last):
  File "/home/keshav/.local/bin/pinion", line 8, in <module>
    sys.exit(cli())
  File "/home/keshav/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/keshav/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/keshav/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/keshav/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/keshav/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/keshav/.local/lib/python3.8/site-packages/pinion/ui.py", line 83, in generate
    generate(specification=yaml.load(specification),
  File "/home/keshav/.local/lib/python3.8/site-packages/pinion/generate.py", line 213, in generate
    fSource = generateImage(board.GetFileName(), outputdir / "front.png",
  File "/home/keshav/.local/lib/python3.8/site-packages/pinion/generate.py", line 140, in generateImage
    subprocess.run(command, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pcbdraw', '--shrink', '0', '--style', 'rendered', 'grover_system_ctlr_hw/grover_system_ctlr_hw.kicad_pcb', '/tmp/tmpp85ab36o/img.svg']' returned non-zero exit status 2.
```
I am wondering whether the correct version of pcbdraw has been installed.
```
pip show pcbdraw
Name: PcbDraw
Version: 1.0.0
Summary: Utility to produce nice looking drawings of KiCAD boards
Home-page: https://github.com/yaqwsx/PcbDraw
Author: Jan Mrázek
Author-email: email@honzamrazek.cz
License: UNKNOWN
Location: /home/keshav/.local/lib/python3.8/site-packages
Requires: pyyaml, numpy, Pillow, click, pybars3, pcbnewTransition, lxml, pyVirtualDisplay, mistune, svgpathtools
Required-by: Pinion
```

Pinion version:
```
pip show pinion
Name: Pinion
Version: 0.2.0
Summary: Create interactive pinout diagrams for KiCAD PCBs
Home-page: https://github.com/yaqwsx/Pinion
Author: Jan Mrázek
Author-email: email@honzamrazek.cz
License: UNKNOWN
Location: /home/keshav/.local/lib/python3.8/site-packages
Requires: ruamel.yaml, pcbnewTransition, pcbdraw, click
Required-by: 
```

Cheers

**Comment by yaqwsx** [comment]
There was a wrongly specified version of PcbDraw in the `setup.py`. We required `>=0.8` instead of `~=0.8`. This allowed the users to use Pinion with PcbDraw v1 for which it has not been adapted yet.

I pushed the initial changes to ensure compatibility in fcd0f5aa39bed8fd091ff8d82c546f0bec3400ba (there's still more work to be done to bring in the new functionality of v1, but at the moment, it should work as used to).

If you install the upstream version, Pinion will work again. I will try to make a new release soon.
