### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable " when trying to generate plotted

### ISSUE THREAD

**Issue by Getiks** [yaqwsx/Pinion#41]
Hi, I tried to generate my PCB but was unable because of the error. I was able to generate an image with PCBDraw.

Traceback (most recent call last):
  File "C:\Program Files\KiCad\7.0\bin\Lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\KiCad\7.0\bin\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\KiCad\7.0\bin\Scripts\pinion.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\ui.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\ui.py", line 105, in generatePlotted
    generate(specification=yaml.load(specification),
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\generate.py", line 327, in generate
    fSource, bSource = imageGenerator(board, outputdir)
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\ui.py", line 98, in generateImages
    return generateDrawnImages(board, outputdir, dpi, {
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\generate.py", line 261, in generateDrawnImages
    fSource = generateImage(board.GetFileName(), outputdir / "front.png",
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pinion\generate.py", line 192, in generateImage
    image = plotter.plot()
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pcbdraw\plot.py", line 1051, in plot
    self._build_libs_path()
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pcbdraw\plot.py", line 1156, in _build_libs_path
    for l in self.libs:
TypeError: 'NoneType' object is not iterable

Even if I'm not sure if it's necessary, I leave the whole project + the YALM file.
[PinionProject.zip](https://github.com/yaqwsx/Pinion/files/11558402/PinionProject.zip)

**Comment by N0cynym** [comment]
Hello I have the same issue with kicad 7.0.2 pcb file.

**Comment by Getiks** [comment]
After searching other error, i saw that #36 had the fix to the issue.
After the fix I was able to generate normaly.
